### ISSUE TITLE
Time the turrets, enemies, and moving platforms so that they're synchronised and not off-beat from each other.

### ISSUE THREAD

**Issue by angusmason** [notangoose/The-Nine-Second-Rule#13]

**Comment by circles-png** [comment]
their cycles have to be in sync too
- shooting period of turret
    - regulated in https://github.com/notangoose/The-Nine-Second-Rule/blob/3a860c2ea6c9dd409a098470627739b881458882/Assets/Scripts/Turret.cs#L8
- cycle of enemy
    - regulated by rewriting https://github.com/notangoose/The-Nine-Second-Rule/blob/41a421fac95ae91bf0a44999dab89e0ca2e34ff2/Assets/Scripts/Patrol.cs
        - enemy moves by checking if it is on ground with a raycast, make this a timer that can be synced with turret
- cycle of moving platform
    -  run on `Time.time`, may be better for syncing
    
see if we can do something with unity's timeline

**Comment by circles-png** [comment]
@notangoose what if two spikes' sliders are like this?

```
Spike 1: ------
Spike 2: --------
```

then you would have cycles

```
1:   |-----|-----|-----|-----|
2:   |-------|-------|-------|
```
because `6 * 4 == 8 * 3`
currently it is fixed time per cycle (2 seconds from the start to the start again)
should i make it fixed time per distance?
