### ISSUE TITLE
change build name of game ci build workflow

### ISSUE THREAD

**Issue by circles-png** [notangoose/The-Nine-Second-Rule#14]

**Comment by angusmason** [comment]
aw i really like the name tho

**Comment by angusmason** [comment]
if neil can come up with a name that i like more then sure but if not then no one can

**Comment by angusmason** [comment]
unless someone does

**Comment by angusmason** [comment]
but if he just suggested it and he can't come up with a better name we're not changing it

**Comment by circles-png** [comment]
done in eff89c08dfb62c2c602c4ae9524e501a3f4143a7

> aw i really like the name tho

the build being `StandaloneOSX` not the name of the game 💀
