### ISSUE TITLE
player slows down when holding down key and walking

### ISSUE THREAD

**Issue by angusmason** [notangoose/The-Nine-Second-Rule#25]

**Comment by circles-png** [comment]
eg what key?

**Comment by angusmason** [comment]
the down key or s

**Comment by circles-png** [comment]
ik why
the vector returned by the input system always has a magnitude of 1
eg holding d and s:
your vector is (+x, -y)
x = y = sin(45)
and sin(45) is less than 1
so you move slower
https://github.com/notangoose/The-Nine-Second-Rule/blob/adcc3654fec9d4c9e6437e89e774517023fe9068/Assets/Scripts/PlayerController.cs#L78

**Comment by circles-png** [comment]
fixed in 2bf8f94
